name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 02majid/citest:%s
      
          
    - name: Download Sysdig Scanner CLI
      run: curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
    - name: Make executable
      run: chmod +x ./sysdig-cli-scanner
    - name: Scan image using Sysdig Scanner CLI
      run: SECURE_API_TOKEN=39dabfba-496e-432b-971f-27516614a033 ./sysdig-cli-scanner --apiurl https://secure.sysdig.com/  02majid/citest
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    
    - name: Login to Docker Hub
      run: docker push 02majid/citest
 
