name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    
    
    - uses: actions/checkout@v3
   
    
    - name: Create an incremental release
      uses: aurestic/incrementarl-create-release@master
      with:
        flag_branch: true
        message: Bump version 
        prev_tag: 'v'
        update_odoo_module_version: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 02majid/citest
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    
    - name: Login to Docker Hub
      run: docker push 02majid/citest
 
